name: build

on:
  workflow_dispatch:
    inputs:
      reference:
        required: true
        description: Reference to the image to build. It triggers the build of any images that depend on it

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        if: ${{ !env.ACT }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Tree
        run: go run ./cmd/tree ${{ github.event.inputs.reference }}

      - name: Build
        run: go run ./cmd/build ${{ env.ACT && '--dry-run' }} ${{ github.event.inputs.reference }}

      - name: Push
        run: |
          for reference in $(go run ./cmd/tree --depth 1 ${{ github.event.inputs.reference }}); do
            ${{ env.ACT && 'echo' }} docker push ${reference}
          done

      - name: Trigger
        run: |
          for reference in $(go run ./cmd/tree --strip 1 --depth 1 --pack ${{ github.event.inputs.reference }}); do
            echo trigger ${reference}
            echo '{
              "ref": "${{ github.ref }}",
              "inputs": {
                "reference": "'${reference}'"
              }
            }' | tee __data

            ${{ env.ACT && 'echo' }} curl \
              --silent \
              --user :${{ secrets.WORKFLOW_PAT }} \
              --request POST \
              --header "Accept: application/vnd.github.v3+json" \
              --data-binary "@__data" \
              ${{ github.api_url }}/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches
          done
